### ISSUE TITLE
Gather Project Review

### ISSUE THREAD

**Issue by mp1pro** [SalmonKing72/tdd-gather-jm#1]
### Criteria 1: Single-Item API Implementation
* _Score Level:_ 4/4
* _Comment(s):_ All Single-Item API Implementation were done correctly
 
### Criteria 2: Single-Item View Implementation
* _Score Level:_ 4/4
* _Comment(s):_ The view implementations successfully tested the DOM's rendering.
 
### Criteria 3: Implementation of Single-Item Server Test Cases
* _Score Level:_ 4/4
* _Comment(s):_ The routes and server tests were done well.
 
### Criteria 4: Implementation of Single-Item Feature Test Cases
* _Score Level:_ 4/4
* _Comment(s):_ All the feature test cases were done correctly. 

### Criteria 5: Test Case Results (Are all Test Cases Passing?)
* _Score Level:_ 4/4
* _Comment(s):_ All test cases passed on running `npm test`
 
### Overall Score: 20/20
The project ran correctly and returned the correct test cases. I would suggest using comments more often.

**Comment by SalmonKing72** [comment]
@mp1pro, thank you for the feedback on the project. I'll keep it all in mind as I work through the capstone.
